package org.gnoss.apiWrapper.ApiModel;

import java.util.List;
import java.util.Map;

/**
 * Represents a Concept according to the Ontology
 * @author GNOSS
 */
public class Concept {
    
    private String subject;
    private String identifier;
    private Map<String, String> prefLabel;
    private List<Concept> narrower;
    private List<Concept> relatedTo;
    private String symbol;
    
    /**
     * Subject of the Concept. If this property is empty will be generated by the source and the identifier automatically
     * @return subject of the concept
     */
    public String getSubject() {
        return subject;
    }
    
    /**
     * Subject of the Concept. If this property is empty will be generated by the source and the identifier automatically
     * @param subject Subject of the concept
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }
    
    /**
     * Identifier of the Concept
     * @return identifier of the concept
     */
    public String getIdentifier() {
        return identifier;
    }
    
    /**
     * Identifier of the Concept
     * @param identifier Identifier of the concept
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }
    
    /**
     * Name to represents the Concept. The key is the language (es, en, de, eu, ...) and the value is the Name in the indicated language.
     * @return preferred label map
     */
    public Map<String, String> getPrefLabel() {
        return prefLabel;
    }
    
    /**
     * Name to represents the Concept. The key is the language (es, en, de, eu, ...) and the value is the Name in the indicated language.
     * @param prefLabel Preferred label map
     */
    public void setPrefLabel(Map<String, String> prefLabel) {
        this.prefLabel = prefLabel;
    }
    
    /**
     * Subjects of the Narrowers of this Concept
     * @return list of narrower concepts
     */
    public List<Concept> getNarrower() {
        return narrower;
    }
    
    /**
     * Subjects of the Narrowers of this Concept
     * @param narrower List of narrower concepts
     */
    public void setNarrower(List<Concept> narrower) {
        this.narrower = narrower;
    }
    
    /**
     * Subjects of the Concept related with this Concept in the same level
     * @return list of related concepts
     */
    public List<Concept> getRelatedTo() {
        return relatedTo;
    }
    
    /**
     * Subjects of the Concept related with this Concept in the same level
     * @param relatedTo List of related concepts
     */
    public void setRelatedTo(List<Concept> relatedTo) {
        this.relatedTo = relatedTo;
    }
    
    /**
     * Depth of the Concept
     * @return symbol of the concept
     */
    public String getSymbol() {
        return symbol;
    }
    
    /**
     * Depth of the Concept
     * @param symbol Symbol of the concept
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
}